# Generated by Django 6.0.4 on 2026-05-15 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('recording_path', models.CharField(blank=True, max_length=500)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='invites.invite')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy', 'Copy Attempt'), ('paste', 'Paste Attempt'), ('cut', 'Cut Attempt'), ('fullscreen_exit', 'Exited Full Screen'), ('webcam_lost', 'Webcam Disconnected'), ('right_click', 'Right Click')], max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot_path', models.CharField(blank=True, max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exam_sessions.session')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_score', models.FloatField(blank=True, null=True)),
                ('manual_score', models.FloatField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_sessions.session')),
            ],
            options={
                'db_table': 'answers',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
