# Generated by Django 6.0.4 on 2026-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
    ]
