# Generated by Django 6.0.4 on 2026-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_application_full_name_application_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='screening_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
