# Generated by Django 6.0.4 on 2026-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_blacklist_phone_blacklist_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='preferred_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
