# Generated by Django 6.0.4 on 2026-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobpost_preferred_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
