# Generated by Django 6.0.4 on 2026-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
