# Generated by Django 6.0.4 on 2026-05-15 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_mins', models.PositiveIntegerField(help_text='Total time allowed in minutes')),
                ('pass_mark_pct', models.PositiveIntegerField(default=50, help_text='Minimum percentage score to pass')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer / Essay')], max_length=20)),
                ('body', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order within the test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.test')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order_index'],
            },
        ),
    ]
