# Generated by Django 6.0.4 on 2026-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='job_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
